#!/usr/bin/env node
// index-tools.mjs — seeds one memory per openClaw-exposed tool so a smaller
// agent can retrieve the right tool semantically via find_tool(intent).
//
// Input:  /tmp/openclaw-tools.json  (array of { server, tool, purpose })
//         generated by the one-line extractor from gateway.log, e.g.:
//           python3 -c "..." > /tmp/openclaw-tools.json
//
// Output: one memory per tool, category='tool', tags include server + name,
//         metadata carries the raw registry row, source='tool-index',
//         all scoped to project 'vectormemory-schritt-3' (the project this
//         indexing is part of).
//
// Idempotent: MemoryService.create() dedups near-duplicates by cosine
// similarity (>0.92). Re-running refreshes via touch rather than insert.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const mcpCfg = JSON.parse(await fs.readFile(path.join(ROOT, ".mcp.json"), "utf8"));
const env = mcpCfg.mcpServers["vector-memory"].env;
for (const k of Object.keys(env)) process.env[k] ||= env[k];

const DIST = path.join(ROOT, "mcp-server/dist");
const { MemoryService }     = await import(path.join(DIST, "services/supabase.js"));
const { ProjectService }    = await import(path.join(DIST, "services/projects.js"));
const { createEmbeddingProvider } = await import(path.join(DIST, "services/embeddings.js"));

const INPUT = process.argv[2] || "/tmp/openclaw-tools.json";
const SCOPE_PROJECT = process.argv[3] ?? "vectormemory-schritt-3";
const tools = JSON.parse(await fs.readFile(INPUT, "utf8"));

const embeddings = createEmbeddingProvider();
const memories   = new MemoryService(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, embeddings);
const projects   = new ProjectService(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

let projectId = null;
if (SCOPE_PROJECT) {
  const p = await projects.getBySlug(SCOPE_PROJECT);
  if (p) projectId = p.id;
  else console.warn(`Project '${SCOPE_PROJECT}' not found — indexing unscoped.`);
}

console.log(`Indexing ${tools.length} tools (scope=${projectId ? SCOPE_PROJECT : "global"})`);
let ok = 0, skipped = 0;

// Hand-curated trigger phrases per tool — English + German synonyms —
// generated dynamically from the literal tool name. Improves recall for
// noisy / translated queries since nomic-embed-text's multilingual
// performance is mediocre for German→English.
function triggerPhrases(name, purpose) {
  const phrases = new Set();
  const bareName = name.replace(/^vector-memory__/, "").replace(/_/g, " ");
  phrases.add(bareName);
  // Split camelCase / snake_case into token hints
  phrases.add(name.replace(/_/g, " "));
  // Purpose with stopwords stripped
  phrases.add(purpose);
  return [...phrases];
}

for (const t of tools) {
  // Lean content: literal name first (FTS hit), purpose second (vector hit),
  // triggers third (alt phrasings for fuzzy queries). No boilerplate that
  // dominates the embedding.
  const fullName = t.server === "functions" ? t.tool : `${t.server}.${t.tool}`;
  const triggers = triggerPhrases(t.tool, t.purpose);
  const content = [
    fullName,
    t.purpose,
    triggers.filter((p) => p !== t.purpose).join(" · "),
  ].filter(Boolean).join("\n");

  const tags = ["tool", t.server, t.tool.split("__")[0]];
  if (t.tool.includes("__")) tags.push(t.tool.split("__")[1]);

  try {
    const m = await memories.create({
      content,
      category: "tool",
      tags: [...new Set(tags)],
      source: "tool-index",
      importance: 0.7,
      pinned: true, // tools should never decay away — they're infrastructure
      metadata: { registry: t, indexed_at: new Date().toISOString() },
      project_id: projectId,
    });
    const isDup = new Date(m.updated_at).getTime() - new Date(m.created_at).getTime() > 1000;
    if (isDup) { skipped++; }
    else       { ok++; }
    process.stdout.write(isDup ? "." : "+");
  } catch (err) {
    console.error(`\nFAIL ${fullName}: ${err.message}`);
  }
}

console.log(`\n\nDone. inserted=${ok} deduped=${skipped} total=${tools.length}`);
console.log("\nVerify with: find_tool('<your intent>')  once the MCP tool ships,");
console.log("or raw:  recall(query='wie sende ich push', category='tool')");
